Foxer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cartsys.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^auth/', include('authsys.urls')),
    url(r'^', include('picture.urls')),
]

authsys/urls.py
from django.conf.urls import url
from . import views

app_name = 'authsys'
urlpatterns = [
    url(r'^$', views.home_auth, name='home_auth'),
    url(r'^reg/$', views.reg, name='reg'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

authsys/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    login = models.CharField(max_length=100)
    name = models.CharField(max_length=100, blank=True)
    surname = models.CharField(max_length=100, blank=True)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    status = models.IntegerField(default=0)
    balance = models.FloatField(default=0.0)

    def __str__(self):
        return self.login

authsys/forms.py
from django import forms


class RegForm(forms.Form):
    login = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)


class AuthForm(forms.Form):
    login = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

authsys/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import RegForm, AuthForm
from .models import User
from cabinet.models import Sale
from cartsys.models import Cart
from Foxer.utils import base_args

import os


# Create your views here.
def home_auth(request):
    args = base_args(request)
    try:
        if request.session['login']:
            return HttpResponseRedirect(reverse('picture:home', args=()))
    except KeyError:
        pass
    args['form'] = AuthForm()
    return render(request, 'authsys/auth.html', args)


def reg(request):
    args = base_args(request)
    try:
        if request.session['login']:
            return HttpResponseRedirect(reverse('picture:home', args=()))
    except KeyError:
        pass
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            login = form.cleaned_data['login']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            if not User.objects.filter(login=login).exists():
                user = User(login=login, email=email, password=password)
                user.save()
                cart = Cart(user=user)
                cart.save()
                sale = Sale(user=user)
                sale.save()
                request.session.set_expiry(60*60*24*30)
                request.session['login'] = login
                request.session['password'] = password
                os.mkdir('media/authors/%s' % login)
                os.mkdir('media/buyer/%s' % login)
                return HttpResponseRedirect(reverse('picture:home', args=()))
    else:
        args['form'] = RegForm()
    return render(request, 'authsys/reg.html', args)


def login(request):
    args = base_args(request)
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            login = form.cleaned_data['login']
            password = form.cleaned_data['password']
            if User.objects.filter(login=login, password=password).exists():
                request.session.set_expiry(60*60*24*30)
                request.session['login'] = login
                request.session['password'] = password
                return HttpResponseRedirect(reverse('picture:home', args=()))
    else:
        args['form'] = AuthForm()
    return render(request, 'authsys/auth.html', args)


def logout(request):
    try:
        del request.session['login']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('picture:home', args=()))

authsys/templates/authsys/auth.html
{%extends 'picture/base.html'%}
{%load staticfiles%}

{%block main%}
<div class="authsys_form">
    <form action="{%url 'authsys:login'%}" method="POST">
        {%csrf_token%}
        <label for="login">логин</label><br>
        {{form.login}}<br>
        <label for="password">пароль</label><br>
        {{form.password}}<br>
        <div class="wrap_but">
            <input type="submit" value="авторизация"/>
            <a href="{%url 'authsys:reg'%}">регистрация</a>
        </div>
    </form>
</div>

{%endblock%}

authsys/templates/authsys/edit.html
{%extends 'picture/base.html'%}
{%load staticfiles%}

{%block main%}
<form action="" method="POST" class="authsys_form" style="margin: 40px 0 40px 60px;">
{%csrf_token%}
<p>Изменить данные</p><br>
<label for="first_name">имя</label><br>
{{form.first_name}}<br>
<label for="last_name">фамилия</label><br>
{{form.last_name}}<br>
<label for="email">email</label><br>
{{form.email}}<br>
<label for="old_password">старый пароль</label><br>
{{form.old_password}}<br>
<label for="new_password">новый пароль</label><br>
{{form.new_password}}<br>
<input type="submit" value="сохранить"/>
{%if password_error%}
{{password_error}}
{%else%}
<p> {{result_message}}</p>
{%endif%}
</form>
{%endblock%}

authsys/templates/authsys/reg.html
{%extends 'picture/base.html'%}
{%load staticfiles%}

{%block main%}
<div class="authsys_form">
    <form action="{%url 'authsys:reg'%}" method='POST'>
        {%csrf_token%}
        <label for="login">логин</label><br>
        {{form.login}}<br>
        <label for="email">почта</label><br>
        {{form.email}}<br>
        <label for="password">пароль</label><br>
        {{form.password}}<br>
        <div class="wrap_but">
            <input type="submit" value="регистрация"/>
            <a href="{%url 'authsys:home_auth'%}">авторизация</a>
        </div>
    </form>
</div>
{%endblock%}