Foxer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cartsys.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^auth/', include('authsys.urls')),
    url(r'^', include('picture.urls')),
]

authsys/urls.py
from django.conf.urls import url
from . import views

app_name = 'authsys'
urlpatterns = [
    url(r'^$', views.home_auth, name='home_auth'),
    url(r'^reg/$', views.reg, name='reg'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

cabinet/urls.py
from django.conf.urls import url
from . import views

app_name = 'cabinet'
urlpatterns = [
    url(r'^$', views.home_cabinet, name='home_cabinet'),
    url(r'^profil/$', views.profil, name='profil'),
    url(r'^profil/upload/$', views.upload, name='upload'),
    url(r'^profil/publication/$', views.publication, name='publication'),
    url(r'^profil/publication/delete/(?P<pk>\d*)/$',
        views.delete_publication, name='delete_publication'),
    url(r'^profil/sold/$', views.sale, name='sale'),
    url(r'^profil/purchases/$', views.purchase, name="purchase"),
]

cartsys/urls.py
from django.conf.urls import url
from . import views


app_name = 'cartsys'
urlpatterns = [
    url(r'^$', views.home_cart, name='home_cart'),
    # url(r'^add/$', views.add_in_cart, name='add_in_cart'),
    # url(r'^delete/$', views.delete_from_cart, name='delete_from_cart'),
    url(r'payment/$', views.payment, name='payment'),
]

picture/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'picture'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<pk>\d*)/$', views.home_picture, name='home_picture'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

picture/models.py
from django.db import models
from authsys.models import User
from django.utils import timezone

import os


# Create your models here.
def get_upload_image(self, filename):
    return os.path.join('authors', self.user.login, filename)


class Picture(models.Model):
    user = models.ForeignKey(User)
    path = models.ImageField(upload_to=get_upload_image)
    name = models.CharField(max_length=100, blank=True)
    price = models.FloatField(default=0.0)
    sale_count = models.IntegerField(default=0)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return '%s/%s' % (self.user.login, self.name)

picture/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from Foxer.utils import base_args
from picture.models import Picture
from cartsys.models import Cart
from cartsys.forms import AddToCart, RemoveFromCart

import datetime
import random


# Create your views here.
def home(request):
    args = base_args(request)
    end = timezone.now()
    start = end - datetime.timedelta(days=1)
    new_pubs = list(Picture.objects.filter(published_date__range=(start, end)))
    random.shuffle(new_pubs)
    args['new_pubs'] = new_pubs[:6]
    args['lid_sales'] = list(Picture.objects.order_by('sale_count'))[:6]
    return render(request, 'picture/home.html', args)


def home_picture(request, pk):
    args = base_args(request)
    args['picture'] = Picture.objects.get(pk=pk)
    if Cart.objects.filter(user__login=args['login'],
                           picture=args['picture'].pk).exists():
        args['form'] = RemoveFromCart({'pict': args['picture'].pk})
        args['exist'] = True
    else:
        args['form'] = AddToCart({'pict': args['picture'].pk})
        args['exist'] = False
    if request.method == 'POST':
        if args['login']:
            if request.POST['operation'] == 'delete':
                pict_pk = request.POST['pict']
                picture = Picture.objects.get(pk=pict_pk)
                cart_user = Cart.objects.get(user__login=args['login'])
                cart_user.picture.remove(picture)
            elif request.POST['operation'] == 'add':
                pict_pk = request.POST['pict']
                picture = Picture.objects.get(pk=pict_pk)
                cart_user = Cart.objects.get(user__login=args['login'])
                cart_user.picture.add(picture)
                cart_user.save()
            return HttpResponseRedirect(reverse('picture:home_picture',
                                                args=(pict_pk,)))
    return render(request, 'picture/picture.html', args)

picture/templates/picture/base.html
{%load staticfiles%}
<html>
    <head>
        <title>{%block title%}FoxerPictures{%endblock%}</title>
        <link rel="stylesheet" type="text/css" href="{%static 'picture/style.css'%}"/>
        <link rel="stylesheet" type="text/css" href="{%static 'authsys/auth_style.css'%}"/>
        <link rel="stylesheet" type="text/css" href="{%static 'cabinet/cabinet_style.css'%}"/>
        <link rel="stylesheet" type="text/css" href="{%static 'cartsys/cart_style.css'%}"/>
        <script type="text/javascript" src="{%static 'picture/jquery-3.1.1.min.js'%}"></script>
        <script type="text/javascript" src="{%static 'picture/script.js'%}"></script>
    </head>
    <body>
        <nav class="top_menu">
            <div class="top_menu_left">
                <a class="top_menu_items" href="doc/">о FoxerPictures</a>
                <a class="top_menu_items" href="doc/forclients">Покупателям</a>
                <a class="top_menu_items" href="doc/forauthors">Авторам</a>
            </div>
            <div class="top_menu_right">
                {%if not login%}
                <a class="top_menu_items" href="{%url 'authsys:home_auth'%}">вход</a>
                {%else%}
                <a class="top_menu_items" href="{%url 'cartsys:home_cart'%}">корзина({{num_pic}})</a>
                <span class="top_menu_items" id="toolbar">{{login}}</span>
                {%endif%}
            </div>
            <ul id="toolbar_menu">
                <a href="{%url 'cabinet:home_cabinet'%}"><li>кабинет</li></a>
                <a href="#"><li>помощь</li></a>
                <a href="{%url 'authsys:logout'%}"><li>выход</li></a>
            </ul>
        </nav>
        <div class="main_header">
            <div class="main_logo">
                <a href="{%url 'picture:home'%}">
                    <img class="logo" src="{%static 'picture/images/logo.png'%}"/>
                </a>
            </div>
            <div class="main_search">
                <div class="search_in clearfix">
                    <div class="search_input"><input type="text" id="search_line"></div>
                    <div class="search_button"><input type="submit" value="найти"></div>
                </div>
                <div class="search_example">
                    <p>Например, <u>пингвины</u></p>
                </div>
            </div>
        </div>
        <div class="main clearfix">
            {%block main%}{%endblock%}
        </div>
        <div class="main_footer clearfix">
            <div class="wrap_columns clearfix">
                <div class="footer_column_1">
                    <ul>
                        <li><b>+ 7 (955) 930 82 70</b></li>
                        <li><b>ask@foxer.ru</b></li>
                        <span>*по вопросам покупки, поиска избражений</span>
                        <li><b>aut@foxer.ru</b></li>
                        <span>*по вопросам авторов о работе фотобанка, а так же о сотрудничестве с нами</span>
                    </ul>
                </div>
                <div class="footer_column_2">
                    <ul>
                        <p><a href="doc/forclients">Для покупателя</a></p>
                        <li><a href="doc/">о фотобанке</a></li>
                        <li><a href="doc/payment">об оплате</a></li>
                        <li><a href="doc/about_license">лицензии</a></li>
                    </ul>
                    <ul>
                        <p><a href="doc/forauthors">Для авторов</a></p>
                        <li><a href="">о сотрудничестве</a></li>
                        <li><a href="">система рейтингов</a></li>
                        <li><a href="">правила работы с фотобанком</a></li>
                    </ul>
                    <ul>
                        <p>Реклама</p>
                        <li><a href="">банеры FoxerPictures</a></li>
                        <li><a href="">размещение рекламы на сайте</a></li>
                    </ul>
                </div>
                <div class="footer_column_3">
                    <ul>
                        <p>Популярные темы</p>
                        <li><a href="">новые публикации</a></li>
                        <li><a href="">лидеры продаж</a></li>
                        <li><a href="">покупателям</a></li>
                        <li><a href="">авторам</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>

picture/templates/picture/home.html
{%extends 'picture/base.html'%}
{%load staticfiles%}
{%block main%}
<div class="container">
    <h1 class="about_header">Фотобанк FoxerPictures - продажа фотографий и иллюстраций</h1>
</div>
<div class="container clearfix border_bot">
    <div class="left_column">
        <ul class="list">
            <li>Пакеты избражений с большой скидкой</li>
            <li>Только качественные фотографии и иллюстрации</li>
            <li>Подбор изображений по вашему запросу</li>
            <li>Индивидуальная работа с покупателем</li>
        </ul>
    </div>
    <div class="right_column">
        <img class="home_slide" src="{%static 'picture/images/home_slider/home_slide_1.jpg'%}" alt=""/>
    </div>
</div>
<div class="container clearfix border_bot">
    <div class="left_column">
        <h2 class="news_header"><a href="news/">Новости фотобанка FoxerPictures</a></h2>
        <ul class="list_news">
            <li><span class="date">12.01.17</span><a href="news/3">Новый поиск по ключевым словам</a></li>
            <li><span class="date">30.12.16</span><a href="news/2">FoxerPicture дарит скидки на новый год!</a></li>
            <li><span class="date">26.12.16</span><a href="news/1">Новый пакет - А7</a></li>
        </ul>
    </div>
</div>
<div class="container clearfix border_bot">
    <div class="left_column forsomeone">
        <h3><a href="#"><u>Покупателям</u></a></h3> 
        <p>Оплату можно произвести при помощи Visa и MasterCard, а также WebMoney и QIWI.</p>
        <p>Для юридических лиц мы предлагаем оплату безналичным банковским переводом.</p>
        <p>Позвоните нам по телефону +7 (955) 930 82 70 или напишите нам на почту ask@foxer.ru и мы ответим на все ваши вопросы.</p>
    </div>
    <div class="right_column forsomeone">
        <h3><a href="#"><u>Авторам</u></a></h3> 
        <p>Приглашаем фотографов и иллюстраторов к нашему сообществу и начать свою получать прибыль за свою деятельность.</p>
        <p>С каждой продажи автор получает от 50 до 80% отчислений, в зависимости от вашего рейтинга.</p>
    </div>
</div>
<div class="container clearfix">
    <div class="left_column forsomeone">
        <h3>Новые публикации</h3>
        <div class="new_pub clearfix">
            {%for new_pub in new_pubs%}
            <a href="{{new_pub.pk}}"><img src="{{MEDIA_URL}}/media/{{new_pub.path}}"/></a>
            {%endfor%}
        </div>
    </div>
    <div class="right_column forsomeone">
        <h3>Лидеры продаж</h3>
        <div class="new_pub clearfix">
            {%for lid_sale in lid_sales%}
            <a href="{{lid_sale.pk}}"><img src="{{MEDIA_URL}}/media/{{lid_sale.path}}"/></a>
            {%endfor%}
        </div>

    </div>
</div>
{%endblock%}

picture/templates/picture/picture.html
{%extends 'picture/base.html'%}
{%load staticfiles%}

{%block main%}
<div class="topics clearfix">
    <ul>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
        <li><a href="#">lorem ipsum</a></li>
    </ul>
</div>
<div class="wrap_picture_content clearfix">
    <div class="main_picture">
        <div class="wrap_picture">
            <img src="{{MEDIA_URL}}/media/{{picture.path}}" />
        </div>
    </div>
    <div class="about_picture">
        {%if login%}
            {%if exist%}
            <form action="{%url 'picture:home_picture' picture.pk%}" method="POST">
                {%csrf_token%}
                {{form}}
                <input type="hidden" value="delete" name="operation"/>
                <input class="default_but" type="submit" value="удалить из корзины"/>
            </form>
            {%else%}
            <form action="{%url 'picture:home_picture' picture.pk%}" method="POST">
                {%csrf_token%}
                {{form}}
                <input type="hidden" value="add" name="operation"/>
                <input class="default_but" type="submit" value="добавить в корзину"/>
            </form>
            {%endif%}
        {%else%}
        <a href="{%url 'authsys:home_auth'%}">вы не авторезированы</a>
        {%endif%}
        <label class="info_pub">цена: {{picture.price}} руб.</label>
        <label class="info_pub">изображение: #{{picture.pk}}</label>
        <label class="info_pub">автор: <u>@{{picture.user}}</u></label>
    </div>
</div>
{%endblock%}