Foxer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cartsys.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^auth/', include('authsys.urls')),
    url(r'^', include('picture.urls')),
]

cabinet/urls.py
from django.conf.urls import url
from . import views

app_name = 'cabinet'
urlpatterns = [
    url(r'^$', views.home_cabinet, name='home_cabinet'),
    url(r'^profil/$', views.profil, name='profil'),
    url(r'^profil/upload/$', views.upload, name='upload'),
    url(r'^profil/publication/$', views.publication, name='publication'),
    url(r'^profil/publication/delete/(?P<pk>\d*)/$',
        views.delete_publication, name='delete_publication'),
    url(r'^profil/sold/$', views.sale, name='sale'),
    url(r'^profil/purchases/$', views.purchase, name="purchase"),
]

cartsys/urls.py
from django.conf.urls import url
from . import views


app_name = 'cartsys'
urlpatterns = [
    url(r'^$', views.home_cart, name='home_cart'),
    # url(r'^add/$', views.add_in_cart, name='add_in_cart'),
    # url(r'^delete/$', views.delete_from_cart, name='delete_from_cart'),
    url(r'payment/$', views.payment, name='payment'),
]

cabinet/models.py
from django.db import models
from authsys.models import User
from picture.models import Picture


# Create your models here.
class Sale(models.Model):
    user = models.OneToOneField(User)
    pictures = models.ManyToManyField(Picture)

    def __str__(self):
        return self.user.login

cabinet/forms.py
from django import forms


class ProfilForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(required=False)
    old_password = forms.CharField(max_length=100,
                                   widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(max_length=100,
                                   widget=forms.PasswordInput, required=False)


class AddJob(forms.Form):
    image_path = forms.ImageField(required=False)


class ChangeStatus(forms.Form):
    status = forms.IntegerField(widget=forms.HiddenInput)

cabinet/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.db.models import Q
from Foxer.utils import base_args_cabinet, get_user
from authsys.models import User
from picture.models import Picture
# from .models import Sale
from .forms import ProfilForm, AddJob, ChangeStatus

import os


# Create your views here.
def home_cabinet(request):
    args = base_args_cabinet(request)
    if args['login']:
        form = ChangeStatus(request.POST or None)
        if form.is_valid():
            user = User.objects.get(login=args['login'])
            user.status = form.cleaned_data['status']
            user.save()
            return HttpResponseRedirect(reverse('cabinet:home_cabinet',
                                                args=()))
        args['form'] = ChangeStatus({'status': 0 if args['status'] else 1})
        return render(request, 'cabinet/base_cabinet.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


def profil(request):
    args = base_args_cabinet(request)
    if args['login']:
        user = get_user(request)
        form = ProfilForm(request.POST or None)
        if form.is_valid():
            user.name = form.cleaned_data['first_name']
            user.surname = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            if user.password == form.cleaned_data['old_password']:
                if form.cleaned_data['new_password'] != '':
                    new_password = form.cleaned_data['new_password']
                    user.password = new_password
                    request.session['password'] = new_password
                else:
                    args['password_error'] = 'пароль не может быть пустым'
            elif form.cleaned_data['old_password'] == '':
                pass
            else:
                args['password_error'] = 'неверный пароль'
            user.save()
            data_user = {'first_name': form.cleaned_data['first_name'],
                         'last_name': form.cleaned_data['last_name'],
                         'email': form.cleaned_data['email']}
            args['form'] = ProfilForm(data_user)
            args['result_message'] = 'данные успешно изменены'
            return render(request, 'cabinet/profil.html', args)
        else:
            data_user = {'first_name': user.name,
                         'last_name': user.surname,
                         'email': user.email}
            args['form'] = ProfilForm(data_user)
            return render(request, 'cabinet/profil.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


def upload(request):
    args = base_args_cabinet(request)
    form = AddJob(request.POST and request.FILES or None)
    if args['login']:
        user = get_user(request)
        if form.is_valid():
            img = request.FILES['image_path']
            p = Picture(user=user, name=img.name, path=img)
            p.save()
            return HttpResponseRedirect(reverse('cabinet:upload', args=()))
        args['form'] = AddJob({'author': user.pk})
        return render(request, 'cabinet/upload.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


def publication(request):
    args = base_args_cabinet(request)
    if args['login']:
        args['publication'] = Picture.objects.filter(~Q(published_date=None),
                                                     user__login=args['login'])
        return render(request, 'cabinet/publication.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


def delete_publication(request, pk):
    args = base_args_cabinet(request)
    if args['login']:
        p = Picture.objects.get(user__login=args['login'], pk=pk)
        os.remove('media/%s' % p.path)
        p.delete()
        return HttpResponseRedirect(reverse('cabinet:publication', args=()))
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


def sale(request):
    args = base_args_cabinet(request)
    if args['login']:
        args['sales'] = Picture.objects.filter(~Q(sale_count=0),
                                               user__login=args['login'])
        return render(request, 'cabinet/sale.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


def purchase(request):
    args = base_args_cabinet(request)
    if args['login']:
        args['purchases'] = Picture.objects.filter(
            sale__user__login=args['login'])
        print(args['purchases'])
        return render(request, 'cabinet/purchase.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))

cabinet/templates/cabinet/base_cabinet.html
{%extends 'picture/base.html'%}
{%load staticfiles%}

{%block main%}
<div class="sidebar clearfix">
    <ul class="sidebar_profil">
        <a  style="color: #E94352;"href="{%url 'cabinet:home_cabinet'%}"><li>мой кабинет</li></a>
        <a href="{%url 'cabinet:profil'%}"><li>мой профиль</li></a>
    </ul>
    {%if status%}
    <ul class="sidebar_author">
        <p>Автор:</p>
        <a href="{%url 'cabinet:upload'%}"><li>загрузка работы</li></a>
        <a href="{%url 'cabinet:publication'%}"><li>мои работы</li></a>
        <a href="{%url 'cabinet:sale'%}"><li>проданные работы</li></a>
        <a href=""><li>договор с FoxerPictures</li></a>
    </ul>
    {%endif%}
    <ul class="sidebar_client">
        <p>Покупатель:</p>
        <a href="#"><li>баланс ({{balance}} руб.)</li></a>
        <a href="{%url 'cabinet:purchase'%}"><li>покупки ({{purchase_count}})</li></a>
        <a href="{%url 'cartsys:home_cart'%}"><li>корзина ({{num_pic}})</li></a>
    </ul>
</div>
<div class="info_cabinet clearfix">
    {%block info_cabinet%}
        <p>Добро пожаловать в личный кабинет FoxerPictures!</p> 
        <p>Здесь Вы можете управлять своим профилем, отслеживать свои покупки и работы. Все купленные работы Вы можете скачать в разделе "Ваши покупки"</p>
        <p>Так же Вы можете выбрать способ оплаты и способ выплат.</p>
        <form action="{%url 'cabinet:home_cabinet'%}" method="POST">
            {%csrf_token%}
            {{form}}
            {%if status == 0%}
            <input class="default_but" type="submit" value="я хочу стать автором"/>
            {%elif status == 1%}
            <input class="default_but" type="submit" value="я не хочу быть автором"/>
            {%endif%}
        </form>
    {%endblock%}    
</div>
{%endblock%}

cabinet/templates/cabinet/profil.html
{%extends 'cabinet/base_cabinet.html'%}
{%load staticfiles%}

{%block info_cabinet%}
<form action="{%url 'cabinet:profil'%}" method="POST" class="authsys_form" style="margin: 40px auto 40px;">
{%csrf_token%}
<p>Изменить данные</p><br>
<label for="first_name">имя</label><br>
{{form.first_name}}<br>
<label for="last_name">фамилия</label><br>
{{form.last_name}}<br>
<label for="email">email</label><br>
{{form.email}}<br>
<label for="old_password">старый пароль</label><br>
{{form.old_password}}<br>
<label for="new_password">новый пароль</label><br>
{{form.new_password}}<br>
<input type="submit" value="сохранить"/>
{%if password_error%}
{{password_error}}
{%else%}
<p> {{result_message}}</p>
{%endif%}
</form>
{%endblock%}

cabinet/templates/cabinet/publication.html
{%extends 'cabinet/base_cabinet.html'%}
{%load staticfiles%}

{%block info_cabinet%}
{%for p in publication%}
<div class="wrap_pub">
    <img class="img_pub" src="{{MEDIA_URL}}/media/{{p.path}}" />
    <label class="img_number">изображение: #{{p.pk}}</label>
    <label class="delete_pub"><a href="{%url 'cabinet:delete_publication' p.pk%}">удалить</a></label>
    <label class="info_pub">стоимость: {{p.price}}</label>
    <label class="info_pub">опубликовано: {{p.published_date|date}}</label>
</div>
{%endfor%}
{%endblock%}

cabinet/templates/cabinet/purchase.html
{%extends 'cabinet/base_cabinet.html'%}
{%load staticfiles%}

{%block info_cabinet%}
{%for purchase in purchases%}
<div class="wrap_pub">
    <img class="img_pub" src="{{MEDIA_URL}}/media/{{purchase.path}}" />
    <label class="img_number">изображение: #{{purchase.pk}}</label>
    <label class="info_pub">стоимость: {{purchase.price}}</label>
</div>
{%endfor%}
{%endblock%}

cabinet/templates/cabinet/sale.html
{%extends 'cabinet/base_cabinet.html'%}
{%load staticfiles%}

{%block info_cabinet%}
{%for sale in sales%}
<div class="wrap_pub">
    <img class="img_pub" src="{{MEDIA_URL}}/media/{{sale.path}}" />
    <label class="img_number">изображение: #{{sale.pk}}</label>
    <label class="info_pub">продано: {{sale.sale_count}}</label>
    <label class="info_pub">стоимость: {{sale.price}}</label>
    <label class="info_pub">опубликовано: {{sale.published_date|date}}</label>
</div>
{%endfor%}
{%endblock%}

cabinet/templates/cabinet/upload.html
{%extends 'cabinet/base_cabinet.html'%}
{%load staticfiles%}

{%block info_cabinet%}
<p>Здесь Вы можете загрузить свою работу на проверку.</p>
<p>После проверки, Ваша работа будет опубликована и появится в разделе "мои работы".</p>
<form class="load_form" action="{%url 'cabinet:upload'%}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <div class="wrap_file">
        {{form.image_path}}
    </div>
    <input type="submit" value="загрузить"/>
</form>
{%endblock%}