Foxer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cartsys.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^auth/', include('authsys.urls')),
    url(r'^', include('picture.urls')),
]

cartsys/urls.py
from django.conf.urls import url
from . import views


app_name = 'cartsys'
urlpatterns = [
    url(r'^$', views.home_cart, name='home_cart'),
    # url(r'^add/$', views.add_in_cart, name='add_in_cart'),
    # url(r'^delete/$', views.delete_from_cart, name='delete_from_cart'),
    url(r'payment/$', views.payment, name='payment'),
]

cartsys/models.py
from django.db import models
from authsys.models import User
from picture.models import Picture


# Create your models here.
class Cart(models.Model):
    user = models.OneToOneField(User)
    picture = models.ManyToManyField(Picture)

    def __str__(self):
        return self.user.login


class Payment(models.Model):
    user = models.ForeignKey(User)
    picture = models.ManyToManyField(Picture, blank=True)
    cost = models.FloatField()

    def __str__(self):
        return self.user.login

cartsys/forms.py
from django import forms


class AddToCart(forms.Form):
    pict = forms.IntegerField(widget=forms.HiddenInput)


class RemoveFromCart(forms.Form):
    pict = forms.IntegerField(widget=forms.HiddenInput)

cartsys/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.db.models import Sum
from picture.models import Picture
from authsys.models import User
from cartsys.models import Cart, Payment
from cabinet.models import Sale
from Foxer.utils import base_args, get_user


# Create your views here.
def home_cart(request):
    args = base_args(request)
    if args['login']:
        if request.method == 'POST':
            pictures = request.POST.getlist('selects')
            if pictures:
                cart_user = Cart.objects.get(user__login=args['login'])
                for picture in pictures:
                    p = Picture.objects.get(pk=picture)
                    cart_user.picture.remove(p)
            return HttpResponseRedirect(reverse('cartsys:home_cart', args=()))
        args['pictures'] = list(Picture.objects.filter(
            cart__user__login=args['login']))
        args['final_sum'] = Picture.objects.filter(
            cart__user__login=args['login']).aggregate(
                Sum('price'))['price__sum']
        return render(request, 'cartsys/home_cart.html', args)
    return HttpResponseRedirect(reverse('authsys:home_auth', args=()))


# def add_in_cart(request):
#     args = base_args(request)
#     if request.method == 'POST':
#         pict_pk = request.POST['pict']
#         picture = Picture.objects.get(pk=pict_pk)
#         cart_user = Cart.objects.get(user__login=args['login'])
#         cart_user.picture.add(picture)
#         cart_user.save()
#         return HttpResponseRedirect(reverse('picture:home_picture',
#                                             args=(pict_pk,)))
#     return render(request, 'picture/home.html', args)


# def delete_from_cart(request):
#     args = base_args(request)
#     if args['login']:
#         if request.method == 'POST':
#             pict_pk = request.POST['pict']
#             picture = Picture.objects.get(pk=pict_pk)
#             cart_user = Cart.objects.get(user__login=args['login'])
#             cart_user.picture.remove(picture)
#             return HttpResponseRedirect(reverse('picture:home_picture',
#                                                 args=(pict_pk,)))
#     return render(request, 'picture/home.html')


def payment(request):
    args = base_args(request)
    if args['login']:
        if request.method == 'POST':
            sales_sum = Picture.objects.filter(
                cart__user__login=args['login']).aggregate(
                    Sum('price'))['price__sum']
            user = get_user(request)
            if user.balance-sales_sum > 0:
                sales = Picture.objects.filter(cart__user__login=user.login)
                pay = Payment(user=user, cost=sales_sum)
                pay.save()
                cart = Cart.objects.get(user__login=user.login)
                user_sale = Sale.objects.get(user=user)
                for sale in sales:
                    author = User.objects.get(picture__pk=sale.pk)
                    author.balance += sale.price
                    user.balance -= sale.price
                    author.save()
                    user.save()
                    sale.sale_count += 1
                    sale.save()
                    user_sale.pictures.add(sale)
                    user_sale.save()
                    pay.picture.add(sale)
                    pay.save()
                    cart.picture.remove(sale)
            return HttpResponseRedirect(reverse('cabinet:home_cabinet',
                                                args=()))

cartsys/templates/cartsys/home_cart.html
{%extends 'picture/base.html'%}
{%load staticfiles%}

{%block main%}
<div class="wrap_cart clearfix">
    {%if pictures%}
    <div class="column_sales clearfix">
        <form class="sales_info" action="{%url 'cartsys:home_cart'%}" method="POST">
            {%csrf_token%}
            <table>
                <tr>
                    <th colspan="3"><input type="submit" value="удалить из корзины"/></th>
                </tr>
                {%for picture in pictures%}
                <tr>
                    <td class="check_column"><input type="checkbox" name="selects" value="{{picture.pk}}"></td>
                    <td class="img_column"><img src="{{MEDIA_URL}}/media/{{picture.path}}"></td>
                    <td class="info_column">
                        <label>изображение: #{{picture.pk}}</label>
                        <label>автор: {{picture.user}}</label>
                        <label>цена: {{picture.price}}руб.</label>
                    </td>
                </tr>
                {%endfor%}
            </table>
        </form>
    </div>
    <div class="final_cost clearfix">
        <label>общая сумма заказа: {{final_sum}}руб.</label><br>
        <form action="{%url 'cartsys:payment'%}" method="POST">
            {%csrf_token%}
            <input type="submit" value="купить"/>
        </form>
    </div>
    {%endif%}
</div>
{%endblock%}